### ISSUE TITLE
Module stuck in loading screen

### ISSUE THREAD

**Issue by RD001** [hermanho/MMM-GooglePhotos#89] opened 2020-09-06 07:34 UTC
If internet connection is established after few minutes of Magic Mirror start then MMM-GooglePhotos module got stuck in "Loading..." screen. 
![Stuck](https://user-images.githubusercontent.com/30950594/92320735-40dd3200-f041-11ea-81bd-e0304c135bd1.jpg)

**Comment by ChrisAcrobat** [comment] 2020-09-07 15:33
Was you able to successfully follow the [Get token.json](https://github.com/ChrisAcrobat/MMM-GooglePhotos#get-tokenjson) instructions?
How does your MMM-GooglePhotos configuration look?

**Comment by RD001** [comment] 2020-09-07 17:03
> Was you able to successfully follow the [Get token.json](https://github.com/ChrisAcrobat/MMM-GooglePhotos#get-tokenjson) instructions?
> How does your MMM-GooglePhotos configuration look?

Module is working fine when PI is already connected to internet and I start the Magic Mirror.
Steps to reproduce - 
1. Disconnect the internet.
2. Start the Magic Mirror.
3. Wait for 2-3 minutes.
4. Connect the internet. 
Note: I wait 10-15 minutes. Should I have wait longer ?

**Comment by Viperzee** [comment] 2020-11-08 18:11
I am having the same problem.

**Comment by nagaculun** [comment] 2020-12-05 18:19
I am seeing the Loading error as well.

This is what the pm2 logs says.


`1|mm  | [2020-12-05 10:15:11.464] [ERROR]
1|mm  | (node:20024) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN photoslibrary.googleapis.com
1|mm  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
1|mm  | [2020-12-05 10:15:11.465] [ERROR]
1|mm  | (node:20024) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN photoslibrary.googleapis.com
1|mm  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
1|mm  | [2020-12-05 10:15:11.473] [ERROR]  (node:20024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
1|mm  | [2020-12-05 10:15:11.474] [ERROR]  (node:20024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
1|mm  | [2020-12-05 10:15:11.476] [ERROR]  (node:20024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1|mm  | [2020-12-05 10:15:11.477] [ERROR]  (node:20024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by howardginsburg** [comment] 2020-12-10 13:49
I think the issue is that the module is trying to connect to the internet before the pi has connected to your wifi.  There's a setting under the Raspberry Pi Configuration called "Network at Boot".  Once I ticked that setting, things seem to be running smoothly all the time.

**Comment by Blaze212** [comment] 2020-12-17 22:50
I have the same issue.... It not an internet connection issue since I can hit the web before launching the module.  
The module was working a week or two ago, and I have not changed anything. A reboot did not seem to solve the issue.
```
[2020-12-17 16:46:05.415] [ERROR]  (node:1182) UnhandledPromiseRejectionWarning: Error: invalid_grant
    at createError (/home/pi/magicMirror/modules/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/magicMirror/modules/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/pi/magicMirror/modules/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

[2020-12-17 16:46:05.416] [ERROR]  (node:1182) UnhandledPromiseRejectionWarning: Error: invalid_grant
    at createError (/home/pi/magicMirror/modules/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/magicMirror/modules/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/pi/magicMirror/modules/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

[2020-12-17 16:46:05.417] [ERROR]  (node:1182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-12-17 16:46:05.417] [ERROR]  (node:1182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-12-17 16:46:05.418] [ERROR]  (node:1182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-12-17 16:46:05.418] [ERROR]  (node:1182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Blaze212** [comment] 2020-12-18 00:14
I figured out my issue. My token had expired. It'd be nice if the google return error stated that the token was expired... 
I deleted my current token, re-allowed permissions via the google portal and its all good to go again

**Comment by captaincapybara** [comment] 2021-01-11 19:08
@Blaze212 how do you re-allow permissions via the google portal, I am having the same loading issue as you.

**Comment by Blaze212** [comment] 2021-01-12 01:27
Delete the token.json file, and then run ```node generate_token.js``` again like in the initial instructions

**Comment by captaincapybara** [comment] 2021-01-12 20:51
do I have to do this every so often? is there a fix where the token won't expire and I won't have to do this again?

**Comment by captaincapybara** [comment] 2021-01-12 20:57
also thanks @Blaze212 for your solution!

**Comment by ChrisAcrobat** [comment] 2021-01-12 23:40
@RD001 and @Viperzee: Do you still have this problem? Have you tried reinitize the js-token as suggested by @Blaze212?

**Comment by Blaze212** [comment] 2021-01-13 00:30
@captaincapybara the token refreshes constantly while the module is running. If you turn off your mirror for either 1 hour or 1 day (I cant remember....) then the token expires and you have to remove it and re-authenticate.

**Comment by ChrisAcrobat** [comment] 2021-01-13 07:39
Oh, that explains why I also had to reinitize it after my Pi was offline for awhile!

**Comment by Viperzee** [comment] 2021-01-13 07:50
I had mine off for a while on the shelf. After reading all this may go back and look into it again. I really like to get this to work.

**Comment by aneaville** [comment] 2021-01-15 20:17
Excluding token authorization, I have confirmed that if the module starts without internet, it is unable to recover. I fixed by retrying the initialization every 1 min until successful.

**Closed as completed** 2021-01-22 23:40 UTC
